spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    discovery:
      enabled: false
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: eventticket
    password: eventticket!

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
eureka:
  client:
    enabled: false
    register-with-eureka: false

management:
  endpoints:
    jmx:
      domain: ${spring.application.name}

management.security.enabled: false

security:
  basic:
    enable: false
  ignored: /**